;;; EXE: test/run-d8.py
;;; FLAGS: --spec
;;; STDIN_FILE: third_party/testsuite/exports.wast
(;; STDOUT ;;;
assert_invalid error:
  third_party/testsuite/exports.wast:5:44: function variable out of range (max 1)
assert_invalid error:
  third_party/testsuite/exports.wast:8:76: duplicate function export "a"
assert_invalid error:
  third_party/testsuite/exports.wast:11:55: duplicate function export "a"
1/1 tests passed.
;;; STDOUT ;;)
